id: A728CB972
base_file: fACAA.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:14:57.519314
  last_modified_at: 2022-05-31 05:14:57.519317
