id: A728CB972
base_file: f043B.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:14:57.503506
  last_modified_at: 2022-05-31 05:14:57.503513
